<?php

namespace AppBundle\Repository;

/**
 * ApiKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
