<?php

namespace AppBundle\Repository;

/**
 * UniversityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
*/

class ShareRepository extends \Doctrine\ORM\EntityRepository
{
  
}
