<?php

namespace AppBundle\Repository;

/**
 * StudentsAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
