<?php

namespace AppBundle\Repository;

/**
 * StudentsAnswerListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentsAnswerListRepository extends \Doctrine\ORM\EntityRepository
{
}
